SECRET: ENC[AES256_GCM,data:iI4GLZJD,iv:VJofiNDq7hpc6hrkYiIOMW6u1cNPhX/G2kLCwqWEWhQ=,tag:ABf3UHXnFQ15GUFq1jBosA==,type:str]
sops:
    age:
        - recipient: age1595c6n7r3zu0aql8qeehlulds6g4cvavmphsyauk9uddks5hpuzqcg7c4u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdGs3dnNRRGoxZ3NCZWxj
            cDIyV3BNZnRCSVBYQVZyKytmRTY0aXRXNFNFCkpVVWtjTXF1YW51Y2U2L0NIcnNw
            NldyWFBadFBhR2JZY2hJa3UxQlY3ZEUKLS0tIEZTa3REMEE1NFFQNHE2RXZRRmpU
            Q1FIempZanpZNlRkRHJaL2h3bXp2T0UKlkxqr7LfA0+aaqyx1RABVdQq4E+Jc/df
            uG1tJOs5A8VPTO+4/fy0U0U7worgZaCEIliBld0ecO2MYnfK78/NnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-24T19:54:42Z"
    mac: ENC[AES256_GCM,data:gyT+GUYmP91b5L6x+n2O8+4c1oaHpNNorGkXqS/lQJ/a4qFWasUH+MhRNcfPcGTT2KcsLJmgwTpnf0XPo07dKMgM6j44DlEzQ77dvMg58ThCNtkeSLk1EDcEe6lxm8tDCatt0r0uWBUhphle7Esy5CauXvUrrKZJzdciT9pI1Js=,iv:A3MtMN4Hd0G5ttrdra6xBsdyUA5xP8HnGgFkSkzRGs4=,tag:BTwmaqSW8HnSkvlHDWszIA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
